version: '3.8'

services:
  backend:
    build: .
    container_name: sabpaisa-qr-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - WEBHOOK_PORT=3001
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - HDFC_API_KEY=${HDFC_API_KEY}
      - HDFC_API_SECRET=${HDFC_API_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - sabpaisa-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: sabpaisa-postgres
    environment:
      - POSTGRES_USER=${DB_USER:-sabpaisa}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sabpaisa123}
      - POSTGRES_DB=${DB_NAME:-sabpaisa_qr}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - sabpaisa-network
    restart: unless-stopped

networks:
  sabpaisa-network:
    driver: bridge

volumes:
  postgres_data: