version: '3.8'

services:
  sabpaisa-backend:
    build: .
    image: sabpaisa/qr-backend:latest
    container_name: sabpaisa-qr-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - APP_VERSION=1.0.0
      # Add your database and API configurations
      # - DB_HOST=mysql
      # - DB_PORT=3306
      # - DB_USER=root
      # - DB_PASSWORD=password
      # - DB_NAME=sabpaisa_qr
      - HDFC_API_URL=https://upitestv2.hdfcbank.com
      - WEBHOOK_BASE_URL=https://your-domain.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - sabpaisa-network
    # Uncomment if using MySQL
    # depends_on:
    #   mysql:
    #     condition: service_healthy

  # Optional: MySQL Database
  # mysql:
  #   image: mysql:8.0
  #   container_name: sabpaisa-mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=sabpaisa_qr
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - sabpaisa-network

  # Optional: Monitoring with Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: sabpaisa-prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - sabpaisa-network

networks:
  sabpaisa-network:
    driver: bridge

volumes:
  mysql_data: